id: IB371B475
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:16:08.762076+00:00
last_modified: 2022-12-14 18:16:08.762083+00:00
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-03-27T17:55:30.044Z'
  creationid: dirk
  eft-text-id: UT22084-079-011
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_384-Glorious_King_of_Tantras_That_Resolves_All_Secrets-v1
bases:
  A000:
    source_metadata: null
    order: 1
    base_file: A000.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
